version: '3.8'
services:
  postgres-test:
    image: postgres:latest
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace_test
    ports:
      - "5433:5432"  # Using a different port to avoid conflicts
